{"name": "Проверка попытки получения заказов у неавторизованного пользователя", "status": "passed", "start": 1712519919279, "stop": 1712519921876, "uuid": "1b244065-f769-43a5-9f2f-672d4ecbeeee", "historyId": "7beee041834e4c4d5fc280429b86f853", "testCaseId": "7beee041834e4c4d5fc280429b86f853", "fullName": "tests.test_get_user_order.TestGetUserOrder#test_get_user_order_without_authorisation_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_order"}, {"name": "subSuite", "value": "TestGetUserOrder"}, {"name": "host", "value": "WIN-R1RFFME11IE"}, {"name": "thread", "value": "7708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_order"}]}